package ru.app.orm;
// Generated 19.06.2015 16:34:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cat generated by hbm2java
 */
public class Cat  implements java.io.Serializable {


     private Integer id;
     private String catName;
     private Set<Prod> prods = new HashSet<Prod>(0);

    public Cat() {
    }

	
    public Cat(String catName) {
        this.catName = catName;
    }
    public Cat(String catName, Set<Prod> prods) {
       this.catName = catName;
       this.prods = prods;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCatName() {
        return this.catName;
    }
    
    public void setCatName(String catName) {
        this.catName = catName;
    }
    public Set<Prod> getProds() {
        return this.prods;
    }
    
    public void setProds(Set<Prod> prods) {
        this.prods = prods;
    }




}


